### ISSUE TITLE
Error during sigma clipping? 

### ISSUE THREAD

**Issue by dylanskeating** [lisadang27/SPCA#31]
I'm getting the following error when trying to run everything_photometry.py:

Analysing ch2 for systematically bad frames...
    Getting frames... Sigma clipping... Traceback (most recent call last):
  File "/homes/mateo/dylank/SPCA/WASP18b_Photometry.py", line 120, in <module>
    ncpu, showPlot=False, savePlot=True)
  File "/homes/mateo/dylank/SPCA/SPCA/frameDiagnosticsBackend.py", line 35, in run_diagnostics
    highpassWidth=highpassWidth, ncpu=ncpu)[0].T
  File "/homes/mateo/dylank/SPCA/SPCA/Photometry_Aperture.py", line 440, in get_lightcurve
    addStack, maskStars, ncpu)
  File "/homes/mateo/dylank/SPCA/SPCA/Photometry_Common.py", line 458, in prepare_images
    image_stack = sigma_clipping(image_stack, sigma=5)
  File "/homes/mateo/dylank/SPCA/SPCA/Photometry_Common.py", line 214, in sigma_clipping
    image_stack[np.any(image_stack.mask[:,lbx:ubx,lby:uby], axis=(1,2))] = np.ma.masked
IndexError: invalid index to scalar variable.

Could this be related to the new update that fixed the RAM issue?

Dylan

**Comment by dylanskeating** [comment]
In the end this turned out to be an issue specific to the set of WASP-18b Ch 2 eclipses--- the data provided by the Spitzer Heritage Archive come from the packaged with Ch 1 images as well for some reason, which the automatic directory structure builder routine did not play nicely with.  Maybe there is a way to handle this situation automatically, or at least mention it in the docs.
